import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Navbar from "@/components/Navbar";
import { Box, Container, Grid } from "@mui/material";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <Navbar />
          <Container maxWidth="lg">
            {" "}
            <Grid container columnSpacing={2} height="calc(100vh - 80px)">
              <Grid item xs={4}>
                <Sidebar />
              </Grid>
              <Grid item xs={8}>
                <Box height="100%">{children}</Box>
              </Grid>
            </Grid>
          </Container>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
